// <auto-generated />
namespace CZE.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cascada_Osoba_Brojtelefona : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cascada_Osoba_Brojtelefona));
        
        string IMigrationMetadata.Id
        {
            get { return "201702211337095_Cascada_Osoba_Brojtelefona"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
