// <auto-generated />
namespace CZE.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UplateKandidata_VezaNaGrupaKandidati : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UplateKandidata_VezaNaGrupaKandidati));
        
        string IMigrationMetadata.Id
        {
            get { return "201703201241524_UplateKandidata_VezaNaGrupaKandidati"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
